# Raspberry Pi 5 GPS/PPS Stratum-1 time server
refclock SHM 0 refid gnss offset 0.0 precision 1e-3 poll 0 filter 3 noselect
refclock PPS /dev/pps0 refid pps lock gnss offset 0.0 poll 3 prefer trust
allow 192.168.1.0/24

keyfile /etc/chrony/chrony.keys
driftfile /var/lib/chrony/chrony.drift
ntsdumpdir /var/lib/chrony

makestep 1.0 3
rtcsync
