refclock SHM 0 refid gnss offset 0.000 precision 1e-3 poll 0 filter 3
refclock PPS /dev/pps0 refid pps lock gnss offset 0.0 poll 3 trust

log tracking measurements statistics

driftfile /var/lib/chrony/chrony.drift
logdir /var/log/chrony
rtcsync
makestep 0.1 3

allow all